package com.example.moneymanager

internal const val PREFS_NAME = "MoneyManager"

internal const val KEY_LANGUAGE = "language"
internal const val KEY_THEME = "theme"
internal const val KEY_CURRENCY = "currency"
internal const val KEY_INCOMES = "incomes"
internal const val KEY_SUBSCRIPTIONS = "subscriptions"
internal const val KEY_EXPENSES = "expenses"
internal const val KEY_TRANSFERS = "transfers"
internal const val KEY_CATEGORIES = "categories"
internal const val KEY_PAYMENT_ACCOUNTS = "payment_accounts"
internal const val KEY_NEXT_PAYMENT_ACCOUNT_ID = "next_payment_account_id"
internal const val KEY_CATEGORY_BUDGETS = "category_budgets"
internal const val KEY_RECURRING_EXPENSES = "recurring_expenses"
internal const val KEY_FAVORITE_CATEGORIES = "favorite_categories"
internal const val KEY_SAVED_TAGS = "saved_tags"
internal const val KEY_SAVED_SUBCATEGORIES = "saved_subcategories"
internal const val KEY_APP_LOCK_ENABLED = "app_lock_enabled"
internal const val KEY_APP_LOCK_PIN_HASH = "app_lock_pin_hash"
internal const val KEY_APP_LOCK_PIN_SALT = "app_lock_pin_salt"
internal const val KEY_APP_LOCK_DEVICE_AUTH = "app_lock_device_auth"
internal const val KEY_MONTHLY_GOAL_AMOUNT = "monthly_goal_amount"
internal const val KEY_MONTHLY_GOAL_INCLUDE_EXPENSES = "monthly_goal_include_expenses"
internal const val KEY_MONTHLY_GOAL_INCLUDE_SUBSCRIPTIONS = "monthly_goal_include_subscriptions"
internal const val KEY_MONTHLY_GOAL_CATEGORIES = "monthly_goal_categories"
internal const val KEY_CASH_AMOUNT = "cash_amount"
internal const val KEY_ACCOUNT_BALANCES = "account_balances"
internal const val KEY_ACCOUNT_LABELS = "account_labels"
internal const val KEY_ROOM_MIGRATION_DONE = "room_migration_done"

internal const val THEME_MINIMAL = "minimal"
internal const val THEME_HELL = "hell"
